version: 1
runtime: php55
api_version: 1

handlers:

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|js)$
  application_readable: true

- url: /index\.php*
  script: index.php

- url: /.*
  script: HW_8.html